#CI pipeline
sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t sathyapraba/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sathyapraba/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-reactapp"
  env: "DockerReactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-809475690252"
  bucket_path: "docker-reactapp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
